spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dearus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: dearusUser
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 9000

jwt:
  secret: your-super-secret-key-should-be-long-enough